stages:
  - lint
  - tests
  - package
  - doc

image: python:3.8

lint:
  stage: lint
  script: |
    echo "*********** Pip Update ***********"
    make update-pip
    echo "*********** Lint Dependency Installation ***********"
    make install-lint
    echo "*********** Lint the Project ***********"
    make lint
  only:
    - merge_requests

tests:
  stage: tests
  script: |
    echo "*********** Disable Logger Outputs ***********"
    sed -i "s/log_cli = true/log_cli = false/" pyproject.toml
    echo "*********** Pip Update ***********"
    make update-pip
    echo "*********** Install the Project with Test Dependencies ***********"
    make install-test
    echo "*********** Test the Project ***********"
    make test-parallel
  only:
    - merge_requests
  # artifacts:
  #   reports:
  #     cobertura: coverage.xml

package:
  stage: package
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created manually
  script: |
    echo "*********** Rename `version` with COMMIT_TAG: $CI_COMMIT_TAG ***********"
    sed -i "s/0.0.0/$CI_COMMIT_TAG/" pyproject.toml
    echo "*********** Pip Update ***********"
    make update-pip
    echo "*********** Build Dependency Installation ***********"
    make install-build
    echo "*********** Build the Project ***********"
    make build
    echo "*********** Publish Dependency Installation ***********"
    make install-publish
    echo "*********** Publish the Project ***********"
    make publish

pages:
  stage: doc
  script: |
    echo "*********** Pip Update ***********"
    make update-pip
    echo "*********** Docs Dependency Installation ***********"
    make install-doc
    echo "*********** Build the project documentation ***********"
    make doc
  # only:
  #   - main
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
      when: manual
  artifacts:
    paths:
      - public
