name: python-template

networks:
  python-template-network:
    name: python-template-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

services:
  python-template-dev:
    image: python-template-dev:latest
    container_name: python-template-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    networks:
      - python-template-network
    # ports:
    #   - 8080:8080
    command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  python-template-prod:
    image: python-template-prod:latest
    container_name: python-template-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    networks:
      - python-template-network
    # ports:
    #   - 8080:8080
    command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
