name: "Setup the Project"
description: "Set up Project by installing dependencies"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        enable-cache: "true"
        cache-suffix: "UV_PYTHON"

    - name: Install project Dependencies
      run: |
        uv sync --frozen
      shell: bash
