# NOTE: exclude
#  Single file/folder -> exclude: examples/.*ipynb
#  Multiple file/folder -> exclude: (^.*<folder_name>/|examples/.*ipynb)

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      #  - id: check-symlinks
      #  - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ["--fix=lf"]
        description: Forces to replace line ending by the UNIX 'lf' character.
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  # - repo: https://github.com/astral-sh/uv-pre-commit
  #   # uv version.
  #   rev: 0.4.20
  #   hooks:
  #     # Update the uv lockfile
  #     - id: uv-lock
  #     # Run the pip compile
  #     - id: pip-compile
  #       args: [requirements.in, -o, requirements.txt]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the Ruff linter.
      - id: ruff
        args: [--exit-non-zero-on-fix, --config=pyproject.toml]
      # Run the Ruff formatter.
      - id: ruff-format
        args: [--config=pyproject.toml]

  # NOTE: It doesn't use pyproject.toml configs. We might enable it the future.
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       files: {{cookiecutter.project_slug}}
  #       additional_dependencies: [types-PyYAML, rich]
  #       args: [
  #           "--strict",
  #           # "--config-file=pyproject.toml",
  #           # "--ignore-missing-imports",
  #         ]
