name: {{cookiecutter.project_name}}

networks:
  {{cookiecutter.project_name}}-network:
    name: {{cookiecutter.project_name}}-network
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

services:
  {{cookiecutter.project_name}}-dev:
    image: {{cookiecutter.project_name}}-dev:latest
    container_name: {{cookiecutter.project_name}}-dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: development
    networks:
      - {{cookiecutter.project_name}}-network
    # ports:
    #   - 8080:8080
    command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
    develop:
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: .
          target: /app
          # Exclude the project virtual environment
          ignore:
            - .venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: ./pyproject.toml

  {{cookiecutter.project_name}}-prod:
    image: {{cookiecutter.project_name}}-prod:latest
    container_name: {{cookiecutter.project_name}}-prod
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    networks:
      - {{cookiecutter.project_name}}-network
    # ports:
    #   - 8080:8080
    command: ["tail", "-f", "/dev/null"] # NOTE: For testing the container
    restart: "no"
