name: Docs Test Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  doc-check:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5

      - name: Install the documentation dependencies
        run: |
          uv sync --frozen --only-group doc

      - name: Test the doc build
        run: |
          make doc-build
