#{% raw %}
name: Test the module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_matrix:
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Disable Logger Outputs
        run: |
          sed -i "s/log_cli = true/log_cli = false/" pyproject.toml

      - name: Install the latest version of uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the Project with Test Dependencies
        run: |
          uv sync --frozen --only-group test

      - name: Test the Project
        run: |
          make test-all-parallel

  # test-single:
  #   runs-on: ubuntu-22.04
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Disable Logger Outputs
  #       run: |
  #         sed -i "s/log_cli = true/log_cli = false/" pyproject.toml

  #     - name: Set up python environment
  #       uses: ./.github/actions/setup-python

  #     - name: Install the Project with Test Dependencies
  #       run: |
  #         uv sync --frozen --only-group test

  #     - name: Test the Project
  #       run: |
  #         make test-all-parallel

  #     # - name: Publish code coverage
  #     #   uses: codecov/codecov-action@v3

#{% endraw %}
