name: Docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Pip updated
        run: |
          pip install --upgrade pip
      - name: Doc installation
        run: |
          make install-doc
      - name: Documenting
        run: |
          make doc
