name: Docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  doc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Pip Update
        run: |
          make update-pip
      - name: Docs Dependency Installation
        run: |
          make install-doc
      - name: Build the project documentation
        run: |
          make doc
      - name: Deploy the documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
