name: Docs via GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Set up cache
        uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - name: Pip Update
        run: |
          make update-pip
      - name: Docs Dependency Installation
        run: |
          make install-doc
      - name: Deploy the documentation to GitHub Pages
        run: |
          make doc-github
