name: Docs Test Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  doc-check:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up the project
        uses: ./.github/actions/setup-project
      - name: Test the doc build
        run: |
          make doc-build
