name: Test the module

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # strategy:
    #   matrix:
    #     python-version: ['3.11', '3.12']
    #     # os: [ubuntu-20.04, ubuntu-22.04]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # - name: Set up Python ${{ matrix.python-version }}
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: ${{ matrix.python-version }}
      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.11'
      - name: Disable Logger Outputs
        run: |
          sed -i "s/log_cli = true/log_cli = false/" pyproject.toml
      # - name: Pip Update
      #   run: |
      #     python -m pip install -U pip
      - name: Install the latest version of rye
        uses: eifinger/setup-rye@v1
        with:
          enable-cache: true
          cache-prefix: 'rye-venv-cache'
      - name: Install the Project with Test Dependencies
        run: |
          rye sync --no-lock
      - name: Test the Project
        # run: make -s test-parallel
        run: |
          python -m pytest -n auto
      # - name: Publish code coverage
      #   uses: codecov/codecov-action@v3
